# Generated by Django 5.1.4 on 2024-12-27 06:21

import apps.documents.enum
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_data", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "documentsfields",
            },
        ),
        migrations.CreateModel(
            name="DocumentField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SIGNED", "SIGNED"),
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("DRAFT", "DRAFT"),
                        ],
                        default=apps.documents.enum.DocumentStatus["DRAFT"],
                        max_length=50,
                    ),
                ),
                (
                    "signing_type",
                    models.CharField(
                        choices=[
                            ("PARALLEL", "PARALLEL"),
                            ("SEQUENTIAL", "SEQUENTIAL"),
                        ],
                        default=apps.documents.enum.SigningType["PARALLEL"],
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("DOCUMENT", "DOCUMENT"), ("TEMPLATE", "TEMPLATE")],
                        default=apps.documents.enum.DocumentType["DOCUMENT"],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "documents_group",
            },
        ),
        migrations.CreateModel(
            name="DocumentsRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("note", models.TextField(null=True)),
            ],
            options={
                "db_table": "documents_recipient",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SIGNER", "SIGNER"),
                            ("APPROVER", "APPROVER"),
                            ("CC", "CC"),
                            ("VIEWER", "VIEWER"),
                        ],
                        default=apps.documents.enum.RecipientRole["SIGNER"],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "recipients",
            },
        ),
    ]
