# Generated by Django 5.1.4 on 2025-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="updated_file_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
