# Generated by Django 5.1.4 on 2024-12-31 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="field",
            table="fields",
        ),
    ]
