# Generated by Django 5.1.4 on 2025-01-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_field_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsharedlink",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentgroup_shared_links",
                to="documents.documentgroup",
            ),
        ),
    ]
