# Generated by Django 5.1.4 on 2024-12-31 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documentsharedlink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentSharedLink",
        ),
    ]
