# Generated by Django 5.1.4 on 2024-12-26 12:22

import apps.documents.enum
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SIGNED", "SIGNED"),
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("DRAFT", "DRAFT"),
                        ],
                        default=apps.documents.enum.DocumentStatus["DRAFT"],
                        max_length=50,
                    ),
                ),
                (
                    "signing_type",
                    models.CharField(
                        choices=[
                            ("PARALLEL", "PARALLEL"),
                            ("SEQUENTIAL", "SEQUENTIAL"),
                        ],
                        default=apps.documents.enum.SigningType["PARALLEL"],
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("DOCUMENT", "DOCUMENT"), ("TEMPLATE", "TEMPLATE")],
                        default=apps.documents.enum.DocumentType["DOCUMENT"],
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_by_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_data", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_groups",
                        to="documents.documentgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
