# Generated by Django 5.1.4 on 2025-01-07 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_documentfield_value"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="document",
            table="documents",
        ),
    ]
