# Generated by Django 5.1.4 on 2025-01-03 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_documentsharedlink_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentsharedlink",
            old_name="document",
            new_name="document_group",
        ),
    ]
