# Generated by Django 5.1.4 on 2025-01-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_rename_document_documentsharedlink_document_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsharedlink",
            name="is_send",
            field=models.BooleanField(default=False),
        ),
    ]
