# Generated by Django 5.1.4 on 2024-12-26 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_documentgroup_document_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentgroup",
            name="document_group",
        ),
    ]
