# Generated by Django 5.1.4 on 2025-01-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_documentsharedlink_is_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsharedlink",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
