# Generated by Django 5.1.4 on 2025-01-03 07:39

import apps.documents.enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_alter_documentsharedlink_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("SMS", "SMS"),
                    ("EMAIL", "EMAIL"),
                    ("OTP", "OTP"),
                    ("NONE", "NONE"),
                ],
                default=apps.documents.enum.RecipientAuthType["NONE"],
                max_length=50,
            ),
        ),
    ]
