# Generated by Django 5.1.4 on 2024-12-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_remove_documentgroup_document_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups_documents",
                to="documents.documentgroup",
            ),
        ),
    ]
