# Generated by Django 5.1.4 on 2025-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_alter_recipient_auth_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsharedlink",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="documentsharedlink",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
