# Generated by Django 5.1.4 on 2025-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0009_rename_is_send_documentsharedlink_is_send_to_recipient_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentgroup",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
