# Generated by Django 5.1.4 on 2025-01-06 03:20

import apps.documents.enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_documentgroup_expire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="is_recipient_sign",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="documentgroup",
            name="validity",
            field=models.CharField(
                choices=[("NO_EXPIRY", "NO_EXPIRY"), ("DATE", "DATE")],
                default=apps.documents.enum.DocumentValidity["NO_EXPIRY"],
                help_text="The validity type of the document (DOCUMENT or Date).",
                max_length=50,
            ),
        ),
    ]
